#!/bin/bash

# this file was made for MAC OS usage, it was never tested on linux

# go to folder
current=`pwd`
cd /Users/marius/Desktop/_spryker/web/demoshop

VAGRANT=`which vagrant`

case "$1" in
	"start")
		$VAGRANT up
		;;
	"stop")
		$VAGRANT suspend
		;;
	"restart")
		$VAGRANT reload
		;;
	"status")
		$VAGRANT status
		;;
	"ssh")
		$VAGRANT ssh
		;;
	*)
		echo " "
		echo ' ./vbox [start|stop|restart|status|ssh]'
		echo " "
		;;
esac

cd $pwd

